### PR TITLE
61-BUNSPACE2024-Create-Button-For-Login

### PR DESCRIPTION
**Pull request by jmorales8**
%{all_commits}
Create a basic img of pillow on the top right of the page.

## Extra Resources

- [The 10 commandments of navigating code reviews](https://techbeacon.com/app-dev-testing/10-commandments-navigating-code-reviews)
- [Google's Code Review Developer Guide](https://google.github.io/eng-practices/review/)

#61

### CODE REVIEW

**Comment by GrpFruit** [comment]
make sure to squash. but also when I click the pillow button It wont route me to the login page

**Comment by jmorales8** [comment]
> make sure to squash. but also when I click the pillow button It wont route me to the login page

yes this is just simply for the button, i could make the route for it too if you want

**Comment by GrpFruit** [comment]
+1

**Comment by jmorales8** [comment]
> Collaborator

I think it should always stay there, it could be used and a log out button too once logged in

**Comment by GrpFruit** [comment]
add login route then merge in +1

**Pull request merged**
