### PR TITLE
82-Connect-API-to-UI-Login-Form

### LINKED ISSUE #82: Connect User sign up/register to UI Login form
Connect the Login API routes to the UI Login page/form.
Create the ability to make users and login to them using the same input fields. 
When creating users, make a basic message saying the user has been created
When logging in, return a basic message saying the user has been and also the jwt token

### PR DESCRIPTION
**Pull request by jmorales8**
Connect the user signup/register form to the backend, can create a user based on the inputs provded 

## Extra Resources

- [The 10 commandments of navigating code reviews](https://techbeacon.com/app-dev-testing/10-commandments-navigating-code-reviews)
- [Google's Code Review Developer Guide](https://google.github.io/eng-practices/review/)

Closes #82

### CODE REVIEW

**Comment by GrpFruit** [comment]
This is awesome. although is this ok? the users info shows up in terminal after user is created
image

why does login make a user in the db?
image
image

**Comment by jmorales8** [comment]
> This is awesome. although is this ok? the users info shows up in terminal after user is created image
> 
> why does login make a user in the db? image image

uh oh, yea that create user via login AINT supposed to happen lmfao. We can get rid of the info stuff. Nice catch on the login stuff. im like 90 percent sure i left it so that its not suppsoed to do anything yet

**Comment by GrpFruit** [comment]
> > This is awesome. although is this ok? the users info shows up in terminal after user is created image
> > why does login make a user in the db? image image
> 
> uh oh, yea that create user via login AINT supposed to happen lmfao. We can get rid of the info stuff. Nice catch on the login stuff. im like 90 percent sure i left it so that its not suppsoed to do anything yet

Right I kinda figured, there's another ticket that is suppose to focus on connecting the login page to the UI. #90

**Comment by jmorales8** [comment]
> > > This is awesome. although is this ok? the users info shows up in terminal after user is created image
> > > why does login make a user in the db? image image
> > 
> > 
> > uh oh, yea that create user via login AINT supposed to happen lmfao. We can get rid of the info stuff. Nice catch on the login stuff. im like 90 percent sure i left it so that its not suppsoed to do anything yet
> 
> Right I kinda figured, there's another ticket that is suppose to focus on connecting the login page to the UI. #90

if anything, i can leave the code as is so that when you modify it, the boiler plate is already more or less there. I can just remove the functionality entirely too and the code that makes it create a user, what do you think?

**Review by GrpFruit — APPROVED** [review]

**Pull request merged**
