### PR TITLE
30-BUNSPACE2024-Add-Music-In-App

### PR DESCRIPTION
**Pull request by jmorales8**
Add music player in app

Allows user to skip to next and prev song in index of songs
There are some console errors that i cant figure out but when i get chagpt4, ill figure it out xd

Stlying i did myself so give feedback

## Extra Resources

- [The 10 commandments of navigating code reviews](https://techbeacon.com/app-dev-testing/10-commandments-navigating-code-reviews)
- [Google's Code Review Developer Guide](https://google.github.io/eng-practices/review/)

Closes [#30, #31 ]

### CODE REVIEW

**Comment by GrpFruit** [comment]
chat didnt cook

**Comment by jmorales8** [comment]
@GrpFruit rebased

**Comment by GrpFruit** [comment]
does this still have the errors when playing a track? there is no changing that right?

**Comment by jmorales8** [comment]
> does this still have the errors when playing a track? there is no changing that right?

No not for now, im sure super conch chat can fix that, i can make a ticket for that later

**Comment by GrpFruit** [comment]
fix conflicts and its good to be approved

**Pull request merged**
